import Link from 'next/link'
import '../styles/global.css'
import Image from 'next/image'
import "./globals.css"
import { Inter } from "next/font/google";
import { ThemeProvider } from "./theme-provider";
import { ThemeSwitcher } from "./ThemeSwitcher";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Abhinav's Blog",
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const header=(
    <header>
      <div className="text-center bg-slate-900 p-8 my-6 rounded-md"> 
      <Image src="/logo.png" alt="Logo" width={48} height={40} className="mx-auto" />
      <Link href="/"><h1 className="text-3x1 text-white text-4xl font-bold mt-4 "> Abhinav's blogsite</h1></Link>
      
               
        <p className='text-slate-300 text-lg mt-4'>Welcome to my blogsite</p>
        
      </div>
    </header>
  )

  const footer=(
    <footer>
      <div className='border-t border-slate-300 mt-6 py-6  text-lg text-center text-slate-500'>
        <h3>Created by-</h3>
        <h2 className="border-b border-slate-500 pb-1">Abhinav Anurag</h2>
      </div>
    </footer>
  )
  return (
    <html lang="en">
      <body>
        <div className='mx-auto  max-w-4xl px-6 text-green-400'>
          {header}
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ThemeSwitcher />
            <main>{children}</main>
          </ThemeProvider>
          {footer}
        </div>
      </body>
    </html>
  )
}
